### PR TITLE
get all possible profiles, devices, app_ids

### PR DESCRIPTION
**Pull request by ehourigan**
commit 8c46a187a0e16b0d1de1a7acef5c9a2513ccbfca only requests one page

### CODE REVIEW

**Comment by KrauseFx** [comment]
@ehourigan did you test just increasing the page size to a very high number?

**Comment by sfransen** [comment]
Ok I will try that

**Comment by ehourigan** [comment]
@KrauseFx I did not try increasing the page size in the API call.  One of my accounts has 140 entries (provisioning profiles) and continues to grow.  At least for my purposes, I am not sure what a suitable large page size should be.

**Comment by sfransen** [comment]
I just raised it to 500 and it doesn't work.
 I have 460 provision profiles and 5000 devices in license.

**Comment by swl367** [comment]
this looks useful and needed! (ASAP for me! thanks)

:) :+1:

**Comment by swl367** [comment]
Is this something that's waiting on review?

**Comment by sgleadow** [comment]
This would be useful for me too. Being able to increase it just as a flat option like in #211 is probably enough for me, but this looks a more flexible solution.

**Comment by mattt** [comment]
Fixed by #216.

**Pull request closed without merging**
