### PR TITLE
Fixed app_ids:add. Added certificates:create and profiles:create functionality with flags

### PR DESCRIPTION
**Pull request by toobulkeh**
I would love feedback on this code and am willing to make improvements to get it merged into master.

Thanks!

PS: Would also love a test framework, just didn't have time to implement it.

### CODE REVIEW

**Comment by joonty** [comment]
:+1: for this - it's the last remaining thing for me to be able to automate absolutely everything!

**Comment by tomdalling** [comment]
:thumbsup: This would be super handy for me too, as it would allow me to automate a few common procedures. Let me know if I can help with this, in any way.

**Comment by vzqwer** [comment]
:thumbsup:

**Comment by igorsales** [comment]
Is anyone having trouble with this pull request? I cannot get it to create push certs for me.

**Pull request closed without merging**
